[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  framework = "astro"
  targetPort = 3000
  port = 8888
  publish = "dist"
  autoLaunch = true
  command = "npm run dev"

[functions]
  node_bundler = "esbuild"
  directory = "netlify/functions"

[build.environment]
  NODE_VERSION = "20"